from nr_common.search import nr_simple_query_parser, nr_luqum_query_parser, nr_query_parser


def test_nr_query_parser_1(app):
    query_string = "title.cs:auto"
    query = nr_query_parser(qstr=query_string)
    assert query.to_dict() == {'match': {'title.cs': {'query': 'auto', 'zero_terms_query': 'none'}}}


def test_nr_query_parser_2(app):
    query_string = "creator.name: Hovorka"
    query = nr_query_parser(qstr=query_string)
    assert query.to_dict() == {
        'nested': {
            'path': 'creator',
            'query': {
                'match': {
                    'creator.name': {
                        'query': 'Hovorka',
                        'zero_terms_query': 'none'
                    }
                }
            }
        }
    }


def test_nr_query_parser_3(app):
    query_string = "auto"
    query = nr_query_parser(qstr=query_string)
    assert query.to_dict() == {
        'query_string': {
            'fields': ['abstract.cs',
                       'abstract.en',
                       'abstract.sk',
                       'abstract.de',
                       'abstract.fr',
                       'abstract.ru',
                       'abstract.es',
                       'abstract.nl',
                       'abstract.it',
                       'abstract.no',
                       'abstract.pl',
                       'abstract.da',
                       'abstract.el',
                       'abstract.hu',
                       'abstract.lt',
                       'abstract.pt',
                       'abstract.bg',
                       'abstract.ro',
                       'abstract.sv',
                       'creator.name',
                       'creator.ORCID',
                       'creator.scopusID',
                       'creator.researcherID',
                       'creator.czenasAutID',
                       'creator.vedidk',
                       'creator.institutionalID',
                       'contributor.name',
                       'contributor.ORCID',
                       'contributor.scopusID',
                       'contributor.researcherID',
                       'contributor.czenasAutID',
                       'contributor.vedidk',
                       'contributor.institutionalID',
                       'contributor.role.title.cs',
                       'contributor.role.title.en',
                       'contributor.role.title.sk',
                       'contributor.role.title.de',
                       'contributor.role.title.fr',
                       'contributor.role.title.ru',
                       'contributor.role.title.es',
                       'contributor.role.title.nl',
                       'contributor.role.title.it',
                       'contributor.role.title.no',
                       'contributor.role.title.pl',
                       'contributor.role.title.da',
                       'contributor.role.title.el',
                       'contributor.role.title.hu',
                       'contributor.role.title.lt',
                       'contributor.role.title.pt',
                       'contributor.role.title.bg',
                       'contributor.role.title.ro',
                       'contributor.role.title.sv',
                       'contributor.role.marcCode',
                       'contributor.role.dataCiteCode',
                       'dateModified',
                       'resourceType.title.cs',
                       'resourceType.title.en',
                       'resourceType.title.sk',
                       'resourceType.title.de',
                       'resourceType.title.fr',
                       'resourceType.title.ru',
                       'resourceType.title.es',
                       'resourceType.title.nl',
                       'resourceType.title.it',
                       'resourceType.title.no',
                       'resourceType.title.pl',
                       'resourceType.title.da',
                       'resourceType.title.el',
                       'resourceType.title.hu',
                       'resourceType.title.lt',
                       'resourceType.title.pt',
                       'resourceType.title.bg',
                       'resourceType.title.ro',
                       'resourceType.title.sv',
                       'resourceType.alias.cs',
                       'resourceType.alias.en',
                       'resourceType.alias.sk',
                       'resourceType.alias.de',
                       'resourceType.alias.fr',
                       'resourceType.alias.ru',
                       'resourceType.alias.es',
                       'resourceType.alias.nl',
                       'resourceType.alias.it',
                       'resourceType.alias.no',
                       'resourceType.alias.pl',
                       'resourceType.alias.da',
                       'resourceType.alias.el',
                       'resourceType.alias.hu',
                       'resourceType.alias.lt',
                       'resourceType.alias.pt',
                       'resourceType.alias.bg',
                       'resourceType.alias.ro',
                       'resourceType.alias.sv',
                       'workIdentifiers.isbn',
                       'workIdentifiers.issn',
                       'workIdentifiers.doi',
                       'workIdentifiers.RIV',
                       'note',
                       'fundingReference.projectID',
                       'fundingReference.projectName',
                       'fundingReference.fundingProgram',
                       'fundingReference.funder.title.cs',
                       'fundingReference.funder.title.en',
                       'fundingReference.funder.title.sk',
                       'fundingReference.funder.title.de',
                       'fundingReference.funder.title.fr',
                       'fundingReference.funder.title.ru',
                       'fundingReference.funder.title.es',
                       'fundingReference.funder.title.nl',
                       'fundingReference.funder.title.it',
                       'fundingReference.funder.title.no',
                       'fundingReference.funder.title.pl',
                       'fundingReference.funder.title.da',
                       'fundingReference.funder.title.el',
                       'fundingReference.funder.title.hu',
                       'fundingReference.funder.title.lt',
                       'fundingReference.funder.title.pt',
                       'fundingReference.funder.title.bg',
                       'fundingReference.funder.title.ro',
                       'fundingReference.funder.title.sv',
                       'fundingReference.funder.formerNames',
                       'fundingReference.funder.aliases',
                       'entities.title.cs',
                       'entities.title.en',
                       'entities.title.sk',
                       'entities.title.de',
                       'entities.title.fr',
                       'entities.title.ru',
                       'entities.title.es',
                       'entities.title.nl',
                       'entities.title.it',
                       'entities.title.no',
                       'entities.title.pl',
                       'entities.title.da',
                       'entities.title.el',
                       'entities.title.hu',
                       'entities.title.lt',
                       'entities.title.pt',
                       'entities.title.bg',
                       'entities.title.ro',
                       'entities.title.sv',
                       'entities.aliases',
                       'entities.formerNames',
                       'publisher'],
            'query': 'auto'
        }
    }
