#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""NUSL id provider"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37580dba0f8'
down_revision = '7b1bed025ddd'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nusl_id',
    sa.Column('nusl_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('nusl_id', name=op.f('pk_nusl_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nusl_id')
    # ### end Alembic commands ###
